matrix:
  include:
    - language: python
      sudo: required
      os: windows
      python: 3.5
      before_install:
        - ls
        - cd Python

    - language: r
      sudo: required
      cache: packages
      before_install:
        - cd R
        - ls
      before_script:
        - sudo bash installODBC.sh
