matrix:
  include:
    - language: python
      python: 3.5
      before_install:
        - cd Python

    - language: r
      cache: packages
      before_install:
        - cd R
        - echo $TESTVAR

