matrix:
  include:
    - language: python
      sudo: required
      python: 3.5
      before_install:
        - cd Python

    - language: r
      sudo: required
      cache: packages
      before_install:
        - cd R
        - ls
        - bash installODBC.sh
