jobs:

- job: 'Python'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python37:
        python.version: '3.7.2'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: cd Python && buildandinstall.cmd
    displayName: 'Build and Install'

  - script: |
      pip install pytest
      cd Python
      pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'Test'
    env:
      SERVER: $(SERVER)
      DATABASE: $(DATABASE)
      USER: $(UID)
      PASSWORD: $(PWD)

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Publish'
  dependsOn: 'Python'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'